version: '3.8'

networks:
  monitoring-network:
    driver: bridge
  app-network:
    external: true
    name: devops-item-manager_app-network

volumes:
  prometheus-data:
  grafana-data:
  loki-data:

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    networks:
      - monitoring-network
      - app-network
    ports:
      - "9090:9090"
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    restart: unless-stopped

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - monitoring-network
      - app-network
    ports:
      - "3000:3000"
    restart: unless-stopped

  loki:
    image: grafana/loki:latest
    container_name: loki
    volumes:
      - loki-data:/loki
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - monitoring-network
    restart: unless-stopped

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - /var/log:/var/log:ro
      - ./promtail/promtail-config.yml:/etc/promtail/config.yml
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - monitoring-network
      - app-network
    restart: unless-stopped
    command:
      - --config.file=/etc/promtail/config.yml
    user: root  # Run as root to ensure access to Docker socket

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - "8081:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw  # Changed to rw
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    networks:
      - monitoring-network
      - app-network
    devices:
      - /dev/kmsg:/dev/kmsg
    security_opt:
      - apparmor:unconfined
    restart: unless-stopped